twig:
    globals:
        enterprise: Confecciones Benito
        admin: "::admin-ext.html.twig"
        author: Ing. Ibrael Espinosa

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    twig.extension.debug:
        class: Twig_Extensions_Extension_Debug
        tags:
            - { name: twig.extension }
